spring.application.name=customer-service
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/customer_service?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
server.port=8081
booking-service.url=${BOOKING_SERVICE_URL:http://localhost:8080}
